# B"H.
image: node

pages:
  script:
    - npm install @11ty/eleventy @11ty/eleventy-navigation @11ty/eleventy-plugin-rss
    - npm run @11ty/eleventy --
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master
