# B"H.
image: node

pages:
  stage: deploy
  script:
    # via https://www.11ty.dev/docs/getting-started/
    - npm init -y
    - npm install --save-dev @11ty/eleventy @11ty/eleventy-navigation @11ty/eleventy-plugin-rss
    - npx @11ty/eleventy --output=public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master
