# B"H.
image: node

pages:
  stage: deploy
  script:
    - apt-get update && apt-get install -y jq && rm -rf /var/lib/apt/lists/*
    # via https://www.11ty.dev/docs/getting-started/
    - npm init -y
    - npm install --save-dev @11ty/eleventy js-yaml @11ty/eleventy-navigation @11ty/eleventy-plugin-rss
    - ./proc_zach.sh
    - npx @11ty/eleventy --output=public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master
