# B"H.
image: node:alpine

before_script: 
    - apk add --no-cache jq
    - NODE_JQ_SKIP_INSTALL_BINARY=true npm i

pages:
  stage: deploy
  script:
    - npm start -- --output=public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master
