# B"H.
azoi:
    title: Azoi
    endpoints:
        web: https://www.azoi.org/
        instagram: azoiapp
        twitter: azoiapp
wrapp:
    title: Wrapp
    endpoints:
        web: http://www.tefillinwrapp.com/
        facebook: TefillinWrapp
        instagram: tefillinwrapp
        twitter: TefillinWrapp
jem:
    title: Jewish Educational Media
    endpoints:
        web: https://jemcentral.org/
        facebook: jewishmedia
        youtube: jewishmedia
        twitter: JEMediaOrg
        instagram: jewish_media
        vimeo: jem
Rebbedrive:
    title: RebbeDrive
    languages: [he, en]
    endpoints:
        web: https://www.Rebbedrive.com/
        youtube: RebbeDrive
        facebook: Rebbe-Drive-930351750466700
living_torah:
    site_id: jem
    title: Living Torah
    endpoints:
        web: https://www.livingtorah.org/
torah_treasure:
    title: Torah Treasure
    endpoints:
        web: https://torahtreasure.com/
        facebook: TorahTreasure2
        youtube: TorahTreasure
small_wonder_puppets:
    title: Small Wonder Puppet Theatre
    endpoints:
        web: http://smallwonderpuppets.com/
        twitter: jewishpuppets
        facebook: SmallWonderPuppetTheatre
my_encounter:
    site_id: jem
    title: My Encounter with the Rebbe
    endpoints:
        web:
            - http://www.1000encounters.com/
        blog:
            - http://myencounterblog.com/
            - https://jemcentral.org/my-encounter/
        facebook: My-Encounter-with-the-Rebbe-311217318011
chabad_org:
    title: Chabad.org
    languages: [he, en, fr, ru, es, de, pt, it]
    endpoints:
        web: https://www.chabad.org/
        facebook: ChabadOrg
        twitter: Chabad
        pinterest: chabad
        instagram: chabadorg
        youtube_channel: UCc0y_E87EUnOW2m2mGJU9Gg
sie:
    title: Sichos in English
    endpoints:
        web: https://www.sie.org/
        facebook: SichosInEnglish
hebrewbooks:
    title: HebrewBooks.org
    endpoints:
        web: https://www.hebrewbooks.org/
        blog: https://blog.hebrewbooks.org/
